version: '3.8'
services:
  deepwiki:
    container_name: deepwiki
    build: .
    ports:
      - "8001:8001"  # API port
      - "3000:3000"  # Next.js port
    environment:
      - OPENAI_MODEL_NAME="yandexgpt/rc"
      - OPENAI_BASE_URL="http://y2o:8520/"
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_EMB_MODEL_NAME=${OPENAI_EMB_MODEL_NAME}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
      - PORT=8001
      - NODE_ENV=production
    networks: 
      - my_app_network
    # volumes:
    #   - C:/Users/User/.adalflow:/root/.adalflow
    #   - ~/.adalflow:/root/.adalflow  # Persist repository and embedding data

  y2o:
    container_name: y2o
    build:
      context: YandexGPT_to_OpenAI
      dockerfile: Dockerfile
    environment:
      - Y2O_BringYourOwnKey=true
      - Y2O_ServerURL=http://0.0.0.0:8520
      - Y2O_LogFile=logs/y2o.log
      - Y2O_LogLevel=INFO
    volumes:
      - ./YandexGPT_to_OpenAI/data:/app/data
      - ./YandexGPT_to_OpenAI/logs:/app/logs
    ports:
      - "8520:8520"
    networks: 
      - my_app_network
    restart: unless-stopped

networks:
  my_app_network:
    driver: bridge 